version: "3.9"
services:

  ### Prefect Database
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    env_file:
      - ./config/postgres.env
    expose:
      - ${POSTGRES_PORT}
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["server"]
  
  ### Prefect Server API and UI
  server:
    image: ${PREFECT_IMAGE}
    restart: always
    volumes:
      - prefect:/root/.prefect
    environment:
      - PREFECT_UI_URL=${PREFECT_UI_URL}
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:${POSTGRES_PORT}/prefect
    ports:
      - ${PREFECT_SERVER_LOCAL_PORT}:${PREFECT_SERVER_LOCAL_PORT}
    depends_on:
      - database
    command: ["prefect", "server", "start", "--port", "${PREFECT_SERVER_LOCAL_PORT}"]
    profiles: ["server"]

      
volumes:
  prefect:
  db:
networks:
  default:
    name: prefect-network